baseURL = "http://yiye.lizhuo.asia/"
languageCode = "zh-CN"
title = "yiye blog"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

## disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "yiye"

[params]
  author = "yiye"
  subtitle = "专注于Android、Java"
  keywords = "java,android,博客,项目管理,python,公众号,小程序"
  description = "做一件事最好的时机是时机是十年前，其次就是现在"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索
  beian = "晋ICP备2020013641号" # 添加备案信息
  fancybox = true # 图片点击放大

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = false  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "我正在读的书"
  name = "我正在读的书"
  url = "https://shixinerya.github.io/mybook/"
  
[[params.links]]
  title = "网盘资源分享"
  name = "网盘资源分享"
  url = "http://onedrive.yiye.show"  

  
## 侧边栏广告位
[[params.ads]]
  title = "【2020双12】ALL IN CLoud 低至1折"
  url = "https://promotion.aliyun.com/ntms/yunparter/invite.html?userCode=q8qrpnxv"
  img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "" ##换成自己的
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
 [params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"


## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "tools"
    name = "工具"
    url = "/tools/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
	
